name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build
        run: yarn build

  test-solidity-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @koil-finance/solidity-utils test

  test-standalone-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @koil-finance/standalone-utils test

  test-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @koil-finance/vault test

  test-pools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Set Yarn version
        run: yarn set version berry
      - name: Add yarn workspaces-tools plugin
        run: yarn plugin import @yarnpkg/plugin-workspace-tools
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspaces foreach --verbose --include @koil-finance/pool-* run test

env:
  CI: true
